### ISSUE TITLE
[FEAT] - implement logger

### ISSUE THREAD

**Issue by r-hannuschka** [q-masters/vsqlik#124]
currently all we use is console.log which is very bad so lets implement a logger for better logging.

**Comment by konne** [comment]
https://github.com/SAP/vscode-logging

**Comment by konne** [comment]
please add possibility to change loglevel in settings

**Comment by r-hannuschka** [comment]
after i play arround a bit open tasks for this are:

- [ ] add global logger to injection token
- [ ] add settings for development logger (log to a file) we have to pass the directory where the logs should be created
- [ ] add settings for log level (off, info, warning, error, debug) for development and default
