### ISSUE TITLE
[FEAT] check directory tree extension 

### ISSUE THREAD

**Issue by konne** [q-masters/vsqlik#17]
please check if is possible to extend the existing directory tree with extra infos.
This would open a way to show the real name off an app even if the directory is only the guid (Qlik Sense for Windows)
It would be also great to give different icons / overlay for published apps / objects,...

**Comment by PLH-Coding** [comment]
We currently show the real name of the Application, which is passed to ApplicationDirectory ( ID and Name ) The Name will shown in Tree and the id is used to load scripts.

Icons this should be possible, there are out some custom icon sets for a tree depends on the project you open ( or file endings / types ).
