### ISSUE TITLE
[FEAT] Settings add filetype 

### ISSUE THREAD

**Issue by r-hannuschka** [q-masters/vsqlik#181]
Currently we print all files (currerntly only variables) in yaml format, so extend the settings to select a file type 

yaml, json, xml

**Comment by r-hannuschka** [comment]
currently implemented in settings but needs to be add to vscode extension. Sad but we have to reload the tree and vscode is not very helpfull to figure out which settings has been changed, so we can register to an event and get 1 function back which only tells true or false if settings be affected. 

Since multiple Settings can changed (Name, Host, Port or FileType) true will not help since we dont know what has been changed or where. So we need to implement our own login to identify which configuration has been changed and what. Useless to reload a tree if the Name or Host has been changed.

And at this point we can even implement if the file view type has been changed (yaml , json or whatever will come) to reload only this on workspace folder and not all which should also improve performance.

**Comment by konne** [comment]
changes of the settings are only allowed on a reconnect. So please just inform the user if a connection for the current changed setting is open, that a disconnect, reconnect have to be done
