### ISSUE TITLE
YAML Edits not working

### ISSUE THREAD

**Issue by mcilwricka** [q-masters/vsqlik#321]
Hi Konrad. I tried to edit a YAML file and changed the sheet description, saved it, and refreshed app in Chrome but change is not visible. Also all of the YAML sheet files have a '!' icon against them in VSCode explorer.

**Comment by r-hannuschka** [comment]
This ! is standard i got this too dont know why this is the case. This is not a real yaml file i name the "virtual file" like that, read out the content -> jsonToyaml -> print thats all.

Let me check this, i think it should work but not sure make alot of changes the last time.

**Comment by r-hannuschka** [comment]
No it is working for me

![image](https://user-images.githubusercontent.com/25415574/86845882-6cc45180-c0aa-11ea-8356-7219966c38ca.png)

and in vscode:

![image](https://user-images.githubusercontent.com/25415574/86845987-8d8ca700-c0aa-11ea-8953-82f39c542072.png)

So i cant reproduce this, have you check you have access rights ? App is not published ?

Best regards,
Ralf
