### ISSUE TITLE
[FEAT] Syntax checks & autocompletion

### ISSUE THREAD

**Issue by konne** [q-masters/vsqlik#405]
The qlik engine supports language server capabilities:

https://qlik.dev/apis/json-rpc/qix/doc#%23%2Fentries%2FDoc%2Fentries%2FCheckScriptSyntax

Implement this via:

https://code.visualstudio.com/api/language-extensions/programmatic-language-features

**Comment by r-hannuschka** [comment]
- [ ] create virtual document to check script syntax if we have only the tab
- [ ] script load command not registered anymore
