### ISSUE TITLE
Run script doesn't update app

### ISSUE THREAD

**Issue by davidwales** [q-masters/vsqlik#542]
**Describe the bug**
Clicking the 'Run script and refresh app from data sources' button appears to successfully run the script. The script output appears in the output window at the bottom of VS Code.

However, when I return to my app in Qlik Sense, it appears as if the script has not run, and the data has not been refreshed. A simple example is that when I uncomment a field, save the script and press the 'Run script...' button, I can't access the field in Qlik Sense. However, if I open the load script editor in Qlik Sense and press the 'Load data' button, it works, and I can access the field.

**To Reproduce**
1. Create a load script with some fields commented out. Make sure it is loaded and working in Qlik Sense. (e.g. You can add fields as dimensions, etc.)
2. In VSQlik, uncomment one of the fields, save and press the 'Run script' button.
3. Wait for the script to finish running in the VSCode Output window.
4. Test to see if you can add the newly uncommented field as a dimension in Qlik. The field will be missing.
5. Click the 'Load data' button in the Qlik Sense load script editor.
6. Test to see if you can add the newly uncommented field as a dimension in Qlik. This should work.

**Expected behavior**
Clicking the 'Run script' button in VSQlik should load the data and update the app.

**Screenshots**
![image](https://user-images.githubusercontent.com/55477181/94219944-497fa480-ff2b-11ea-935d-d1cd551f66ac.png)
The screenshot above shows the output in VS Code from clicking the 'Run script' button.

**Desktop (please complete the following information):**
 - OS: Windows 10 (1909)
 - Browser: Edge (non-Chromium)
 - VSQlik Version: 1.2.0

**Additional context**
The last line of output from running the script in VS Code is just the last table loaded:

```
Organisations << Organisations 245 Lines fetched
```

This is different to the last lines of output when running the script in Qlik Sense:

````
Organisations << Organisations 245 Lines fetched
Creating search index
Search index creation completed successfully

App saved

Finished successfully
0 forced error(s)
0 synthetic key(s)
````

I'm not sure if this is relevant!

**Comment by r-hannuschka** [comment]
@davidwales thx for informing us about that bug, i try to fix this asap because this is is really important.

**Comment by davidwales** [comment]
Thanks for fixing this one! 🚀
This was the main thing preventing me from using VSQlik as my primary Qlik editor.

**Comment by konne** [comment]
@r-hannuschka I like the idea of the keybinding, can you add this already through the extensions itself?
