### ISSUE TITLE
Unable to connect Qlik Desktop

### ISSUE THREAD

**Issue by ot3kcw6c** [q-masters/vsqlik#598]
**Describe the bug**
Not able to connection on a Desktop Version of Qlik.

**To Reproduce**
1. Install Plugin
2. Use the predefined Connection with the Name "Localhost"

**Expected behavior**
Connect to the local running Qlik Sense for Desktop instance.

**Screenshots**
![image](https://user-images.githubusercontent.com/61137563/96226500-04331d80-0f93-11eb-9004-ae837bb058e8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Qlik Sense Version: Qlik Sense Desktop September 2020 Patch 2
 - Visual Studio Code Version: 1.50.1
 - vscode4qlik Version: 1.3.0

**Additional context**
Tried many combinations: Port 4848 Path: /hub Path: /hub/my/work

**Comment by r-hannuschka** [comment]
Hey,

is the server for Qlik Sense Desktop is running if you open your Browsr and go to http:://localhost or https://localhost ? Port and path are not necessary.

Best Regards,
Ralf

**Comment by ot3kcw6c** [comment]
![image](https://user-images.githubusercontent.com/61137563/96228587-0f3b7d00-0f96-11eb-9e11-47cd5e13bd17.png)

Qlik Desktop need Port 4848 to open the hub. But yes: Qlik Sense runs on localhost.

If i open my Browser and open local host: ERR_CONNECTION_REFUSED
If i open http://localhost:4848/hub/my/work: Everything is working

**Comment by r-hannuschka** [comment]
Currently i can not reproduce this, but on the other side i can call directly localhost and come to my authentication form (or simply get redirected to hub/my/work) in windows.

So it working for me but on the other side i can add port:4848 and the server is not found anymore. I need some time to check this one, maybe it is a configuration problem ?

**Comment by ot3kcw6c** [comment]
I didn't changed/manipulated any configuration.

**Comment by r-hannuschka** [comment]
@konne you have an idea about this ?

**Comment by r-hannuschka** [comment]
as discussed with @konne this is a new feature we want to implement asap, currently we can only connect to docker / qlik sense server but not qlik sense desktop.

**Comment by r-hannuschka** [comment]
added new setting for qlik sense desktop, activate checkbox if we handle a QlikSenseDesktop

![image](https://user-images.githubusercontent.com/25415574/96372861-4f068e00-1169-11eb-8f3d-41f0c15425d3.png)

- enable checkbox
- remove path "hub" from path settings this will be added now automatically if we handle a qlik sense desktop
- port should be 4848 

also fixed a bug the port was missing in connection, this was one of the reason why this was not working.

**Comment by r-hannuschka** [comment]
We changed this a little bit again, the setting was removed just enter now

host: localhost
port: 4848
path: ""
not secure: true
auth method: none

in the settings and it should work
