### ISSUE TITLE
Log still prints 'load data completed app saved' after script error

### ISSUE THREAD

**Issue by davidwales** [q-masters/vsqlik#604]
**Describe the bug**
Suppose your script has an error.
Normally the script will stop running when it encounters an error.
In VSQlik, the error message is printed, but at the end the log prints:

```
load data completed
app PMHC MDS saved
<<<
```

I think it should not print this if there was an error!

**To Reproduce**
1. Create a script with an error (e.g. an extra comma before the first item in the LOAD.)
2. Run the script from VSQlik.
3. You will see at the end of the log:

```
load data completed
app PMHC MDS saved
<<<
```

**Expected behavior**
In Qlik Sense, when an error is encountered, the log ends with:

```
Data has not been loaded. Please correct the error and try loading again.
```

**Screenshots**
VSQlik:
![image](https://user-images.githubusercontent.com/55477181/96406406-21821900-122b-11eb-9d18-3ed3026dd538.png)

Qlik Sense:
![image](https://user-images.githubusercontent.com/55477181/96406393-1929de00-122b-11eb-95c6-31e6d097bd9d.png)

**Desktop (please complete the following information):**
 - OS: Windows 1909
 - Browser: Edge
 - VSQlik Version: 1.3.0

**Comment by konne** [comment]
@davidwales we will fix it ASAP

Please can you leave here a rating for the extension
https://marketplace.visualstudio.com/items?itemName=q-masters.vscode-qlik&ssr=false#review-details

**Comment by davidwales** [comment]
Rating completed!
