### ISSUE TITLE
Error messages not displayed as expected

### ISSUE THREAD

**Issue by davidwales** [q-masters/vsqlik#618]
**Describe the bug**
A Qlik script with an error does not print the error to the log.
This is a regression since 1.3.
I suspect this was introduced with the fix for #604.

**To Reproduce**
1. Run a script with an error.
2. The script will stop with `load data finished with errors <<<`, but the errors will not be printed in the log.

**EDIT**: As discussed below, the error message is displayed at the top of the log, rather than at the bottom, and the location of the error is not displayed.

**Expected behavior**
The error message would be printed.

**Desktop (please complete the following information):**
 - Windows 1909
 - Edge
 - VS Qlik Version 1.5.0

**Comment by r-hannuschka** [comment]
By default it should show them errors but they are maybe on bad position

![image](https://user-images.githubusercontent.com/25415574/96690842-79806300-1384-11eb-9109-2e48419f5a20.png)

So the message should be printed top before the messages comes finised with errors, but on the other side i dont have super complicated qlik scripts.

**Comment by konne** [comment]
@davidwales I double-checked this with Ralf and the Error message is visible. We see that the Line there the error occurred is missing and we will add this line.

**Comment by konne** [comment]
![image](https://user-images.githubusercontent.com/1100969/96723358-c416d500-13ae-11eb-88ad-9a256d523b98.png)

**Comment by r-hannuschka** [comment]
rework the format for the error messages to highlight this more

![image](https://user-images.githubusercontent.com/25415574/96747348-74dd9e00-13c8-11eb-9ea2-f41522bc4146.png)

**Comment by davidwales** [comment]
Thanks! You're right, the error was displaying. However, it was displaying before the list of loaded tables, rather than at the end, and it omitted the information about the location of the error.

e.g. With the following load script:

``` qlik
LOAD
    key,
    first_name
Inline [
    key,first_name
    1,Princess
    2,Dread Pirate
    3,Fezzik
];

JOIN
LOAD
    key,
    first_name,
    last_name
Inline [
    key,last_name
    1,Buttercup
    2,Roberts
    4,Humperdinck
];
```

![image](https://user-images.githubusercontent.com/55477181/96789143-5b783880-1440-11eb-9484-6aa72908632a.png)

![image](https://user-images.githubusercontent.com/55477181/96789167-6632cd80-1440-11eb-8c07-5c7ab32b5a0b.png)

@r-hannuschka, your new version looks good!

**Comment by r-hannuschka** [comment]
Yeah but i have to say my old error message wasn't that good ;) Thats the reason we take over the qlik format for errors i think this is also much more informative and improve this extension a bit. So thx for the issue so we could solve this fast.
