### ISSUE TITLE
[Feature] Improve Connection Settings

### ISSUE THREAD

**Issue by r-hannuschka** [q-masters/vsqlik#72]
First create extension, seems to be very good but currently it seems we could only use docker containers for that without adding a specific username or password to login to a real server, can we provide such a feature that we can add a configuration for to add username and password to connect a server ?

Best Regards,
Ralf

**Comment by konne** [comment]
add Setting per Server:
1. fileytpe (yaml, json, xml)
2. ignoreSSL / allowed SSL Thumbprint
3. auth type
4. username / password save -> please show attention message

**Comment by r-hannuschka** [comment]
Moved Files and ssl to new issues since i wont focus this now and this can be closed soon.

@see #180 for ssl and #181 for file type
