### ISSUE TITLE
Enable GitHub discussions feature to enable easier chat between users

### ISSUE THREAD

**Issue by mountaindude** [q-masters/vsqlik#801]
**Is your feature request related to a problem? Please describe.**
I am sure people have lots of good ideas, questions to ask etc.
These sort of things aren't always issues, but the new per-repository discussions feature of GitHub are great for this kind talk. Easy to enable, just a checkbox away in the repo config :).

**Comment by konne** [comment]
@mountaindude you have now the chance to be the first who starts a discussion.
